es:
  enable: true
  index:
    name: mysql-prod-*
  username: elastic
  password: T3pIzg@1234
  timeout: 60
  hosts: 192.168.0.51:9200,192.168.0.52:9200,192.168.0.53:9200
  # 获取最大数量 (ES默认from + size <= 10000 ，超过1W的话如果不配置ES会报错
  size: 10000
export_path: ./