spring:
  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.56.11:3306/test?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
#    username: root
#    password: root
    url: jdbc:postgresql://192.168.56.11:5432/postgres?currentSchema=public
    hikari:
      username: postgres
      password: 123456
    max-idle: 50 #空闲池中最大连接数
    min-idle: 10 #空闲池中最小连接数
    max-wait: 10000
    initial-size: 10
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.spring.framework.web: error
    ga.vabe.*: debug

mybatis-plus:
  mapper-locations: classpath:/ga/vabe/mybatis/dao/*Mapper.xml
  global-config:
    db-config:
      id-type: input
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)